paths:
  /api/products:
    get:
      summary: Obtiene todos los prodcutos de la base de datos
      tags: 
        - Products
      responses:
        "200":
          description: Los productos fueron obtenidos satisfactoriamente de la DB
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Error al tratar de traer todos los productos

    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      requestBody:
        description: Datos del nuevo producto
        requested: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: true
                description: 
                  type: string
                  required: true
                category:
                  type: string
                  required: true
                price:
                  type: number
                  required: true
                thumbnails:
                  type: array
                code:
                  type: number
                  required: true
                stock:
                  type: number
                  required: true
                status:
                  type: boolean
                owner:
                    type: string          
      responses:
        "201":
          description: Producto creado con éxito.
          content:
            application/json:
             schema:
              type: array
              items:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error del servidor. No se pudo crear el producto.

  /api/products/{pid}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string

      responses:
        "200":
          description: Éxito. Devuelve el producto solicitado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado.
        "500":
          description: Error al leer el producto

    put:
      summary: Actualizar un producto por ID
      tags:
        - Products
      description: Nuevos datos del producto
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                category:
                  type: string
                description: 
                  type: string
                price:
                  type: number
                thumbnails:
                  type: array
                stock:
                  type: number
                status:
                  type: boolean
                owner:
                  type: string

      responses:
        "201":
          description: Producto actualizado con éxito.
          content:
            application/json:
              shema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "403":
          description: No esta autorizado a modificar el producto
        "404":
          description: Producto no encontrado.
        "500":
          description: Error del servidor. No se pudo actualizar el producto.

    delete:
      summary: Eliminar un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto a eliminar
          schema:
            type: string
      responses:
       "200":
          description: Producto eliminado con éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
       "404":
          description: Producto no encontrado en la DB
       "500":
          description: Error del servidor. No se pudo eliminar el producto

components:
    schemas:
        Product:
            type: object
            properties:
              _id: 
                type: objectId
                format: bson objectId 
                description: Id autogenerado por MongoDB
              title:
                type: string
                description: Nombre del producto
              description:
                type: string
                description: Descripcion del producto
              price:
                type: number
                description: Precio del producto
              thumbnails:
                type: array
                items:
                  type: string
                  description: Arreglo de fotos del Producto
              code:
                type: number
                description: Codigo del producto debe ser unico e irrepetible
              stock:
                type: number
                description: Cantidad  que hay del producto               
              category:
                type: string
                description: Categoria a la que pertenece el producto
              status:
                type: boolean
                description: Status true = activo, false = desactivado
              owner:
                type: string
                description: Propietario del producto. Esto hace referancia a la colection Users, por defecto se setea user pero puede ser cambiado a un ADMIN o  Premium
            required:
                - title
                - description
                - price
                - code
                - stock
                - category
          